name = 'alt:V Server'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'alt:V Sample Server'
modules = ['js-module']
resources = [
    "client",
    "server",
    "altv-os-freecam-master",
    "altv-dev-tools",
    "altv-os-nametags"
]
debug = true
spawnAfterConnect = false
sendPlayerNames = true